version: '3.5'

services: 
  postgres-latest:
    container_name: gestao-gastos-familiar
    image: postgres:latest
    environment:
      POSTGRES_DB: gestao-gastos-familiar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
    ports:
      - "5440:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
